# Generated by Django 4.2.4 on 2024-03-11 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='musician',
        ),
    ]
