# Generated by Django 4.2.4 on 2024-03-11 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_remove_album_musician'),
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='album.album'),
            preserve_default=False,
        ),
    ]
