# Generated by Django 4.2.4 on 2024-03-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('cars', '0005_comment_email_alter_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ManyToManyField(to='categories.category'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
